package com.lebaoxun.guess.core.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.lebaoxun.guess.entity.GuessTemplateOption;

@Mapper
public interface GuessTemplateOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_template_option
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_template_option
     *
     * @mbggenerated
     */
    int insert(GuessTemplateOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_template_option
     *
     * @mbggenerated
     */
    int insertSelective(GuessTemplateOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_template_option
     *
     * @mbggenerated
     */
    GuessTemplateOption selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_template_option
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GuessTemplateOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guess_template_option
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GuessTemplateOption record);
    
    List<GuessTemplateOption> findByTemplateId(@Param("templateId")Integer templateId);
    
    int deleteByTemplateId(@Param("templateId")Integer templateId);
}